import "dotenv/config";
import mongoose from "mongoose";
import Product from "../models/Product";
import Category from "../models/Category";
import User from "../models/User";

type CliOptions = {
  sellerId: string;
  categoryId: string;
  categoryName: string;
  dryRun: boolean;
};

function parseArgs(): Partial<CliOptions> {
  const args = process.argv.slice(2);
  const options: Record<string, string | boolean> = {};

  for (const arg of args) {
    if (!arg.startsWith("--")) continue;
    const [key, rawValue] = arg.slice(2).split("=");
    if (!key) continue;
    if (rawValue === undefined) {
      options[key] = true;
    } else {
      options[key] = rawValue;
    }
  }

  const result: Partial<CliOptions> = {};
  if (typeof options.sellerId === "string") result.sellerId = options.sellerId;
  if (typeof options.categoryId === "string") result.categoryId = options.categoryId;
  if (typeof options.categoryName === "string") result.categoryName = options.categoryName;
  if (typeof options.dryRun === "boolean") result.dryRun = options.dryRun;
  if (typeof options.dryRun === "string") result.dryRun = options.dryRun === "true";

  return result;
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .trim()
    .replace(/['"]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function buildOptions(): CliOptions {
  const parsed = parseArgs();

  return {
    sellerId:
      parsed.sellerId ??
      process.env.SEED_SELLER_ID ??
      "685ab59e33f273e409dc3eac",
    categoryId: parsed.categoryId ?? process.env.SEED_CATEGORY_ID ?? "phones",
    categoryName:
      parsed.categoryName ?? process.env.SEED_CATEGORY_NAME ?? "Smartphones",
    dryRun:
      parsed.dryRun ??
      (typeof process.env.SEED_DRY_RUN === "string"
        ? process.env.SEED_DRY_RUN === "true"
        : false),
  };
}

async function ensureCategory(categoryId: string, categoryName: string) {
  const existing = await Category.findOne({ categoryId }).select("_id");
  if (existing) return existing;

  console.log(`Creating category ${categoryName} (${categoryId})`);
  return Category.create({
    categoryId,
    categoryName,
    description: `${categoryName} autogenerated by seed script`,
  });
}

type BrandProfile = {
  brand: string;
  slugSegment: string;
  series: string[];
  colors: string[];
  storageOptions: number[];
  displaySizes: number[];
  chipsets: string[];
  os: string;
  displayTechnology: string;
  charging: string;
  basePrice: number;
  priceStep: number;
  priceVariance: number;
  baseStock: number;
  productType: string;
};

type BrandAllocation = {
  profile: BrandProfile;
  quantity: number;
};

function generateProductId(brand: string, index: number): string {
  const prefix = brand.replace(/[^A-Za-z0-9]/g, "").slice(0, 3).toUpperCase() || "PRD";
  const timestamp = Date.now().toString(36).toUpperCase();
  const suffix = index.toString(36).toUpperCase().padStart(2, "0");
  return `${prefix}-${timestamp}-${suffix}`;
}

const APPLE_PROFILE: BrandProfile = {
  brand: "Apple",
  slugSegment: "apple",
  series: ["iPhone 15", "iPhone 15 Plus", "iPhone 15 Pro", "iPhone 15 Pro Max", "iPhone SE"],
  colors: [
    "Midnight",
    "Starlight",
    "Blue Titanium",
    "Natural Titanium",
    "Product Red",
    "Green",
  ],
  storageOptions: [128, 256, 512, 1024],
  displaySizes: [4.7, 6.1, 6.7],
  chipsets: ["A17 Pro", "A16 Bionic", "A15 Bionic"],
  os: "iOS 17",
  displayTechnology: "Super Retina XDR",
  charging: "MagSafe and Qi wireless charging",
  basePrice: 799,
  priceStep: 70,
  priceVariance: 90,
  baseStock: 35,
  productType: "Phone",
};

const SAMSUNG_PROFILE: BrandProfile = {
  brand: "Samsung",
  slugSegment: "samsung",
  series: [
    "Galaxy S24",
    "Galaxy S24+",
    "Galaxy S24 Ultra",
    "Galaxy Z Flip5",
    "Galaxy Z Fold5",
  ],
  colors: [
    "Phantom Black",
    "Cream",
    "Cobalt Violet",
    "Ice Blue",
    "Graphite",
  ],
  storageOptions: [256, 512, 1024],
  displaySizes: [6.2, 6.7, 6.8],
  chipsets: ["Snapdragon 8 Gen 3", "Exynos 2400"],
  os: "Android 14 with One UI 6",
  displayTechnology: "Dynamic AMOLED 2X",
  charging: "45W Super Fast Charging",
  basePrice: 749,
  priceStep: 60,
  priceVariance: 110,
  baseStock: 28,
  productType: "Phone",
};

const OPPO_PROFILE: BrandProfile = {
  brand: "Oppo",
  slugSegment: "oppo",
  series: ["Find X7", "Reno11", "Reno11 Pro", "F25", "A79"],
  colors: [
    "Ocean Blue",
    "Emerald Green",
    "Sunset Gold",
    "Space Black",
    "Glacier Silver",
  ],
  storageOptions: [128, 256, 512],
  displaySizes: [6.4, 6.7],
  chipsets: ["Dimensity 9200", "Snapdragon 8+ Gen 1", "Dimensity 7050"],
  os: "ColorOS 14 (Android 14)",
  displayTechnology: "AMOLED",
  charging: "80W SuperVOOC charging",
  basePrice: 549,
  priceStep: 40,
  priceVariance: 80,
  baseStock: 32,
  productType: "Phone",
};

const ROG_PROFILE: BrandProfile = {
  brand: "ROG",
  slugSegment: "rog",
  series: ["Phone 7", "Phone 7 Ultimate", "Phone 8", "Phone 8 Pro"],
  colors: ["Phantom Black", "Storm White", "Rebel Grey"],
  storageOptions: [256, 512, 1024],
  displaySizes: [6.78],
  chipsets: ["Snapdragon 8 Gen 2", "Snapdragon 8 Gen 3"],
  os: "ROG UI (Android 14)",
  displayTechnology: "165Hz AMOLED",
  charging: "65W HyperCharge with side-mounted port",
  basePrice: 999,
  priceStep: 90,
  priceVariance: 120,
  baseStock: 24,
  productType: "Gaming Phone",
};

const BRAND_ALLOCATIONS: BrandAllocation[] = [
  { profile: APPLE_PROFILE, quantity: 60 },
  { profile: SAMSUNG_PROFILE, quantity: 20 },
  { profile: OPPO_PROFILE, quantity: 10 },
  { profile: ROG_PROFILE, quantity: 10 },
];

type BuildContext = {
  sellerId: mongoose.Types.ObjectId;
  categoryId: mongoose.Types.ObjectId;
  profile: BrandProfile;
  globalIndex: number;
  localIndex: number;
};

function buildProductPayload({
  sellerId,
  categoryId,
  profile,
  globalIndex,
  localIndex,
}: BuildContext): Record<string, unknown> {
  const seriesIndex = localIndex % profile.series.length;
  const generation = Math.floor(localIndex / profile.series.length);
  const series = profile.series[seriesIndex];
  const color = profile.colors[(globalIndex + localIndex) % profile.colors.length];
  const storage = profile.storageOptions[(globalIndex + localIndex) % profile.storageOptions.length];
  const display = profile.displaySizes[localIndex % profile.displaySizes.length];
  const chipset = profile.chipsets[(globalIndex + localIndex) % profile.chipsets.length];

  const modelVariant = generation > 0 ? `${series} Gen ${generation + 1}` : series;
  const modelName =
    profile.brand === "Apple" ? modelVariant : `${profile.brand} ${modelVariant}`;
  const slugBase = `${modelName} ${storage}GB ${color}`;
  const slug = slugify(`${slugBase} ${globalIndex + 1}`);

  const price = Math.round(
    profile.basePrice +
      generation * profile.priceStep +
      seriesIndex * Math.round(profile.priceStep / 2) +
      Math.random() * profile.priceVariance
  );
  const compareAtPrice = price + Math.round(120 + Math.random() * 160);
  const stock = profile.baseStock + ((localIndex + globalIndex) * 3) % 64;

  const images = [
    `https://cdn.example.com/${profile.slugSegment}/${slug}.jpg`,
    `https://cdn.example.com/${profile.slugSegment}/${slug}-alt.jpg`,
  ];

  const description = `${modelName} delivers flagship experiences with a ${display}-inch ${profile.displayTechnology} display, ${chipset} platform, and ${storage}GB of storage in a ${color.toLowerCase()} finish.`;
  const feature = [
    `• ${display}-inch ${profile.displayTechnology} display`,
    `• ${chipset} 5G processor`,
    `• ${storage}GB storage with high-speed flash`,
    `• ${profile.os}`,
    `• ${profile.charging}`,
  ].join("\n");

  const attributes: Record<string, string> = {
    Brand: profile.brand,
    Series: series,
    Model: modelVariant,
    Storage: `${storage}GB`,
    Color: color,
    Display: `${display}\"`,
    Chipset: chipset,
    OS: profile.os,
  };

  const seoTitle = `${modelName} ${storage}GB ${color} | ${profile.brand} ${profile.productType}`;
  const seoDescription = `${modelName} pairs ${profile.displayTechnology} visuals with ${chipset} performance and ${storage}GB storage for discerning users.`;

  const priceFloor = Math.max(price - 40, Math.round(price * 0.88));

  return {
    productId: generateProductId(profile.brand, globalIndex),
    name: modelName,
    slug,
    description,
    feature,
    price,
    compareAtPrice,
    currency: "USD",
    stock,
    category: categoryId,
    seller: sellerId,
    status: "Published",
    tag: [
      "phone",
      profile.brand.toLowerCase(),
      profile.slugSegment,
      `${storage}gb`,
      modelVariant.replace(/\s+/g, "-").toLowerCase(),
    ],
    images,
    primaryImageIndex: 0,
    ratingAvg: Math.round((Math.random() * 1.8 + 3.2) * 10) / 10,
    ratingCount: 50 + Math.floor(Math.random() * 250),
    salesCount: 100 + Math.floor(Math.random() * 4000),
    isTrending: profile.brand === "Apple" || profile.brand === "Samsung",
    dimensions: {
      length: Number((16 + Math.random()).toFixed(1)),
      width: Number((7.5 + Math.random() * 0.6).toFixed(1)),
      height: Number((0.75 + Math.random() * 0.2).toFixed(2)),
    },
    weight: Number((185 + Math.random() * 35).toFixed(0)),
    variants: [],
    attributes,
    seo: {
      title: seoTitle,
      description: seoDescription,
      keywords: [
        profile.brand,
        modelVariant,
        `${profile.brand} smartphone`,
        chipset,
        `${storage}GB phone`,
      ],
    },
    isAdult: false,
    isHazardous: false,
    productType: profile.productType,
    actualPrice: price,
    dealerPrice: Math.round(price * 0.84),
    dedupeKey: `${sellerId.toHexString()}:${slug}`,
    isDeleted: false,
    priceMin: priceFloor,
    priceMax: compareAtPrice,
    cost: Math.round(price * 0.78),
  };
}

function buildAllProducts(
  sellerId: mongoose.Types.ObjectId,
  categoryId: mongoose.Types.ObjectId
): Record<string, unknown>[] {
  const products: Record<string, unknown>[] = [];
  let globalIndex = 0;

  for (const allocation of BRAND_ALLOCATIONS) {
    for (let localIndex = 0; localIndex < allocation.quantity; localIndex += 1) {
      products.push(
        buildProductPayload({
          sellerId,
          categoryId,
          profile: allocation.profile,
          globalIndex,
          localIndex,
        })
      );
      globalIndex += 1;
    }
  }

  return products;
}

async function run() {
  const options = buildOptions();
  const mongoUri = process.env.MONGO_URI;
  if (!mongoUri) throw new Error("MONGO_URI environment variable is required");

  console.log(`Connecting to MongoDB...`);
  await mongoose.connect(mongoUri);
  console.log(`Connected. Preparing seed data...`);

  const seller = await User.findById(options.sellerId).select("_id");
  if (!seller) {
    throw new Error(
      `Seller with id ${options.sellerId} was not found. Please create it before seeding.`
    );
  }
  const category = await ensureCategory(options.categoryId, options.categoryName);

  const sellerId = seller._id as mongoose.Types.ObjectId;
  const categoryId = category._id as mongoose.Types.ObjectId;

  const products = buildAllProducts(sellerId, categoryId);

  const total = products.length;
  console.log("Prepared product distribution:");
  for (const allocation of BRAND_ALLOCATIONS) {
    console.log(`- ${allocation.profile.brand}: ${allocation.quantity}`);
  }
  console.log(`Total products: ${total}`);

  if (options.dryRun) {
    console.log(`Dry run enabled. Generated ${products.length} product payloads.`);
    console.log(products[0]);
    await mongoose.disconnect();
    return;
  }

  const inserted = await Product.insertMany(products, { ordered: false });

  console.log(`Inserted ${inserted.length} products.`);

  await mongoose.disconnect();
  console.log("MongoDB connection closed.");
}

run().catch(async (err) => {
  console.error("Seed script failed:", err);
  try {
    await mongoose.disconnect();
  } catch (disconnectErr) {
    console.error("Failed to disconnect cleanly:", disconnectErr);
  }
  process.exit(1);
});