import "dotenv/config";
import mongoose from "mongoose";
import Product from "../models/Product";
import Category from "../models/Category";
import Brand from "../models/Brand";
import User from "../models/User";

type CliOptions = {
  sellerId: string;
  categoryId: string;
  categoryName: string;
  dryRun: boolean;
};

function parseArgs(): Partial<CliOptions> {
  const args = process.argv.slice(2);
  const options: Record<string, string | boolean> = {};

  for (const arg of args) {
    if (!arg.startsWith("--")) continue;
    const [key, rawValue] = arg.slice(2).split("=");
    if (!key) continue;
    if (rawValue === undefined) {
      options[key] = true;
    } else {
      options[key] = rawValue;
    }
  }

  const result: Partial<CliOptions> = {};
  if (typeof options.sellerId === "string") result.sellerId = options.sellerId;
  if (typeof options.categoryId === "string") result.categoryId = options.categoryId;
  if (typeof options.categoryName === "string") result.categoryName = options.categoryName;
  if (typeof options.dryRun === "boolean") result.dryRun = options.dryRun;
  if (typeof options.dryRun === "string") result.dryRun = options.dryRun === "true";

  return result;
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .trim()
    .replace(/['"]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function escapeRegExp(input: string): string {
  return input.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&");
}

function buildOptions(): CliOptions {
  const parsed = parseArgs();

  return {
    sellerId:
      parsed.sellerId ??
      process.env.SEED_SELLER_ID ??
      "685ab59e33f273e409dc3eac",
    categoryId: parsed.categoryId ?? process.env.SEED_CATEGORY_ID ?? "phones",
    categoryName:
      parsed.categoryName ?? process.env.SEED_CATEGORY_NAME ?? "Smartphones",
    dryRun:
      parsed.dryRun ??
      (typeof process.env.SEED_DRY_RUN === "string"
        ? process.env.SEED_DRY_RUN === "true"
        : false),
  };
}

async function ensureCategory(categoryId: string, categoryName: string) {
  const existing = await Category.findOne({ categoryId }).select("_id");
  if (existing) return existing;

  console.log(`Creating category ${categoryName} (${categoryId})`);
  return Category.create({
    categoryId,
    categoryName,
    description: `${categoryName} autogenerated by seed script`,
  });
}

async function ensureBrand(brandName: string, slug: string) {
  const escapedName = escapeRegExp(brandName);
  const existingByName = await Brand.findOne({
    name: { $regex: new RegExp(`^${escapedName}$`, "i") },
  }).select("_id");
  if (existingByName) return existingByName;

  const escapedSlug = escapeRegExp(slug);
  const existingBySlug = await Brand.findOne({
    slug: { $regex: new RegExp(`^${escapedSlug}$`, "i") },
  }).select("_id");
  if (existingBySlug) return existingBySlug;

  console.log(`Creating brand ${brandName} (${slug})`);
  return Brand.create({ name: brandName, slug, isActive: true });
}

type CategoryDescriptor = {
  id: string;
  name: string;
};

type CategoryRule = {
  match: RegExp;
  category: CategoryDescriptor;
};

type BrandProfile = {
  brand: string;
  brandRecordName: string;
  brandSlug: string;
  slugSegment: string;
  series: string[];
  colors: string[];
  storageOptions: number[];
  displaySizes: number[];
  chipsets: string[];
  os: string;
  displayTechnology: string;
  charging: string;
  basePrice: number;
  priceStep: number;
  priceVariance: number;
  baseStock: number;
  productType: string;
  defaultCategory?: CategoryDescriptor;
  categoryRules?: CategoryRule[];
};

type BrandAllocation = {
  profile: BrandProfile;
  quantity: number;
};

function generateProductId(brand: string, index: number): string {
  const prefix = brand.replace(/[^A-Za-z0-9]/g, "").slice(0, 3).toUpperCase() || "PRD";
  const timestamp = Date.now().toString(36).toUpperCase();
  const suffix = index.toString(36).toUpperCase().padStart(2, "0");
  return `${prefix}-${timestamp}-${suffix}`;
}

const APPLE_PROFILE: BrandProfile = {
  brand: "Apple",
  brandRecordName: "Apple",
  brandSlug: "apple",
  slugSegment: "apple",
  series: ["iPhone 15", "iPhone 15 Plus", "iPhone 15 Pro", "iPhone 15 Pro Max", "iPhone SE"],
  colors: [
    "Midnight",
    "Starlight",
    "Blue Titanium",
    "Natural Titanium",
    "Product Red",
    "Green",
  ],
  storageOptions: [128, 256, 512, 1024],
  displaySizes: [4.7, 6.1, 6.7],
  chipsets: ["A17 Pro", "A16 Bionic", "A15 Bionic"],
  os: "iOS 17",
  displayTechnology: "Super Retina XDR",
  charging: "MagSafe and Qi wireless charging",
  basePrice: 799,
  priceStep: 70,
  priceVariance: 90,
  baseStock: 35,
  productType: "Phone",
  defaultCategory: { id: "phones", name: "Smartphones" },
  categoryRules: [
    { match: /^iPhone 13/i, category: { id: "IPH-13", name: "iPhone 13 Series" } },
    { match: /^iPhone 14/i, category: { id: "IPH-14", name: "iPhone 14 Series" } },
    { match: /^iPhone 15/i, category: { id: "IPH-15", name: "iPhone 15 Series" } },
    { match: /^iPhone 16/i, category: { id: "IPH-16", name: "iPhone 16 Series" } },
    { match: /^iPhone 17/i, category: { id: "IPH-17", name: "iPhone 17 Series" } },
  ],
};

const SAMSUNG_PROFILE: BrandProfile = {
  brand: "Samsung",
  brandRecordName: "Samsung",
  brandSlug: "samsung",
  slugSegment: "samsung",
  series: [
    "Galaxy S24",
    "Galaxy S24+",
    "Galaxy S24 Ultra",
    "Galaxy Z Flip5",
    "Galaxy Z Fold5",
  ],
  colors: [
    "Phantom Black",
    "Cream",
    "Cobalt Violet",
    "Ice Blue",
    "Graphite",
  ],
  storageOptions: [256, 512, 1024],
  displaySizes: [6.2, 6.7, 6.8],
  chipsets: ["Snapdragon 8 Gen 3", "Exynos 2400"],
  os: "Android 14 with One UI 6",
  displayTechnology: "Dynamic AMOLED 2X",
  charging: "45W Super Fast Charging",
  basePrice: 749,
  priceStep: 60,
  priceVariance: 110,
  baseStock: 28,
  productType: "Phone",
  defaultCategory: { id: "SAMSUNG", name: "SAMSUNG" },
};

const OPPO_PROFILE: BrandProfile = {
  brand: "Oppo",
  brandRecordName: "OPPO",
  brandSlug: "oppo",
  slugSegment: "oppo",
  series: ["Find X7", "Reno11", "Reno11 Pro", "F25", "A79"],
  colors: [
    "Ocean Blue",
    "Emerald Green",
    "Sunset Gold",
    "Space Black",
    "Glacier Silver",
  ],
  storageOptions: [128, 256, 512],
  displaySizes: [6.4, 6.7],
  chipsets: ["Dimensity 9200", "Snapdragon 8+ Gen 1", "Dimensity 7050"],
  os: "ColorOS 14 (Android 14)",
  displayTechnology: "AMOLED",
  charging: "80W SuperVOOC charging",
  basePrice: 549,
  priceStep: 40,
  priceVariance: 80,
  baseStock: 32,
  productType: "Phone",
  defaultCategory: { id: "OPPO", name: "OPPO" },
};

const ROG_PROFILE: BrandProfile = {
  brand: "ROG",
  brandRecordName: "ROG",
  brandSlug: "rog",
  slugSegment: "rog",
  series: ["Phone 7", "Phone 7 Ultimate", "Phone 8", "Phone 8 Pro"],
  colors: ["Phantom Black", "Storm White", "Rebel Grey"],
  storageOptions: [256, 512, 1024],
  displaySizes: [6.78],
  chipsets: ["Snapdragon 8 Gen 2", "Snapdragon 8 Gen 3"],
  os: "ROG UI (Android 14)",
  displayTechnology: "165Hz AMOLED",
  charging: "65W HyperCharge with side-mounted port",
  basePrice: 999,
  priceStep: 90,
  priceVariance: 120,
  baseStock: 24,
  productType: "Gaming Phone",
  defaultCategory: { id: "ROG", name: "ROG" },
};

const GOOGLE_PROFILE: BrandProfile = {
  brand: "Google",
  brandRecordName: "Google",
  brandSlug: "google",
  slugSegment: "pixel",
  series: ["Pixel 8", "Pixel 8 Pro", "Pixel 8a", "Pixel Fold", "Pixel 7a"],
  colors: ["Obsidian", "Porcelain", "Hazel", "Bay", "Aloe"],
  storageOptions: [128, 256, 512],
  displaySizes: [6.1, 6.3, 6.7],
  chipsets: ["Google Tensor G3", "Google Tensor G2"],
  os: "Android 14",
  displayTechnology: "OLED",
  charging: "30W fast charging with wireless support",
  basePrice: 599,
  priceStep: 45,
  priceVariance: 75,
  baseStock: 26,
  productType: "Phone",
  defaultCategory: { id: "GOOGLE", name: "GOOGLE" },
};

const XIAOMI_PROFILE: BrandProfile = {
  brand: "Xiaomi",
  brandRecordName: "Xiaomi",
  brandSlug: "xiaomi",
  slugSegment: "xiaomi",
  series: ["Xiaomi 14", "Xiaomi 14 Ultra", "Redmi Note 13", "Redmi K70", "Poco F6"],
  colors: ["Black", "White", "Jade Green", "Silver", "Sunrise Orange"],
  storageOptions: [128, 256, 512],
  displaySizes: [6.36, 6.67, 6.73],
  chipsets: ["Snapdragon 8 Gen 3", "Dimensity 8300-Ultra", "Snapdragon 8 Gen 2"],
  os: "HyperOS (Android 14)",
  displayTechnology: "LTPO AMOLED",
  charging: "90W HyperCharge",
  basePrice: 499,
  priceStep: 40,
  priceVariance: 70,
  baseStock: 30,
  productType: "Phone",
  defaultCategory: { id: "XIAOMI", name: "XIAOMI" },
};

const ONEPLUS_PROFILE: BrandProfile = {
  brand: "OnePlus",
  brandRecordName: "OnePlus",
  brandSlug: "oneplus",
  slugSegment: "oneplus",
  series: ["OnePlus 12", "OnePlus 12R", "OnePlus Open", "OnePlus Nord 3", "OnePlus Nord CE 4"],
  colors: ["Silky Black", "Emerald Green", "Glacier Silver", "Iron Gray", "Celadon Marble"],
  storageOptions: [128, 256, 512],
  displaySizes: [6.43, 6.7, 7.82],
  chipsets: ["Snapdragon 8 Gen 3", "Snapdragon 8 Gen 2", "Dimensity 9000"],
  os: "OxygenOS 14 (Android 14)",
  displayTechnology: "Fluid AMOLED",
  charging: "100W SUPERVOOC",
  basePrice: 549,
  priceStep: 45,
  priceVariance: 85,
  baseStock: 27,
  productType: "Phone",
  defaultCategory: { id: "ONEPLUS", name: "ONEPLUS" },
};

const MOTOROLA_PROFILE: BrandProfile = {
  brand: "Motorola",
  brandRecordName: "Motorola",
  brandSlug: "motorola",
  slugSegment: "motorola",
  series: ["Razr 40 Ultra", "Razr 40", "Edge 40 Pro", "Edge 40", "Moto G Power 5G"],
  colors: ["Viva Magenta", "Satin Blue", "Eclipse Black", "Nebula Green", "Lunar Blue"],
  storageOptions: [128, 256, 512],
  displaySizes: [6.5, 6.6, 6.9],
  chipsets: ["Snapdragon 8 Gen 2", "Dimensity 8020", "Snapdragon 6 Gen 1"],
  os: "Android 14",
  displayTechnology: "pOLED",
  charging: "68W TurboPower",
  basePrice: 449,
  priceStep: 35,
  priceVariance: 65,
  baseStock: 33,
  productType: "Phone",
  defaultCategory: { id: "MOTOROLA", name: "MOTOROLA" },
};

const SONY_PROFILE: BrandProfile = {
  brand: "Sony",
  brandRecordName: "Sony",
  brandSlug: "sony",
  slugSegment: "sony",
  series: ["Xperia 1 V", "Xperia 5 V", "Xperia 10 V", "Xperia Pro-I", "Xperia 1 IV"],
  colors: ["Black", "Khaki Green", "Platinum Silver", "Burgundy", "Slate"],
  storageOptions: [128, 256, 512],
  displaySizes: [6.1, 6.5, 6.7],
  chipsets: ["Snapdragon 8 Gen 2", "Snapdragon 8 Gen 1", "Snapdragon 695"],
  os: "Android 14",
  displayTechnology: "4K OLED",
  charging: "30W USB-C Power Delivery",
  basePrice: 899,
  priceStep: 60,
  priceVariance: 100,
  baseStock: 20,
  productType: "Phone",
  defaultCategory: { id: "SONY", name: "SONY" },
};

const VIVO_PROFILE: BrandProfile = {
  brand: "Vivo",
  brandRecordName: "Vivo",
  brandSlug: "vivo",
  slugSegment: "vivo",
  series: ["X100 Pro", "X100", "V30 Pro", "V30", "iQOO 12"],
  colors: ["Asteroid Black", "Startrail Blue", "Petals White", "Andes Blue", "Legendary Black"],
  storageOptions: [128, 256, 512],
  displaySizes: [6.44, 6.78],
  chipsets: ["Dimensity 9300", "Snapdragon 8 Gen 3", "Snapdragon 7 Gen 3"],
  os: "Funtouch OS 14 (Android 14)",
  displayTechnology: "AMOLED",
  charging: "120W FlashCharge",
  basePrice: 529,
  priceStep: 40,
  priceVariance: 75,
  baseStock: 31,
  productType: "Phone",
  defaultCategory: { id: "VIVO", name: "VIVO" },
};

const BRAND_ALLOCATIONS: BrandAllocation[] = [
  { profile: APPLE_PROFILE, quantity: 10 },
  { profile: SAMSUNG_PROFILE, quantity: 10 },
  { profile: OPPO_PROFILE, quantity: 10 },
  { profile: ROG_PROFILE, quantity: 10 },
  { profile: GOOGLE_PROFILE, quantity: 10 },
  { profile: XIAOMI_PROFILE, quantity: 10 },
  { profile: ONEPLUS_PROFILE, quantity: 10 },
  { profile: MOTOROLA_PROFILE, quantity: 10 },
  { profile: SONY_PROFILE, quantity: 10 },
  { profile: VIVO_PROFILE, quantity: 10 },
];

type CategoryCache = Map<string, mongoose.Types.ObjectId>;

type BuildContext = {
  sellerId: mongoose.Types.ObjectId;
  brandId: mongoose.Types.ObjectId;
  profile: BrandProfile;
  globalIndex: number;
  localIndex: number;
  categoryCache: CategoryCache;
  fallbackCategoryId: string;
};

function resolveCategoryId(
  profile: BrandProfile,
  series: string,
  modelVariant: string,
  categoryCache: CategoryCache,
  fallbackCategoryId: string
): mongoose.Types.ObjectId {
  if (profile.categoryRules) {
    for (const rule of profile.categoryRules) {
      if (rule.match.test(series) || rule.match.test(modelVariant)) {
        const cached = categoryCache.get(rule.category.id);
        if (cached) return cached;
      }
    }
  }

  if (profile.defaultCategory) {
    const cached = categoryCache.get(profile.defaultCategory.id);
    if (cached) return cached;
  }

  const fallback = categoryCache.get(fallbackCategoryId);
  if (fallback) return fallback;

  throw new Error(
    `Unable to resolve category for ${profile.brand} ${modelVariant}. Ensure the category exists.`
  );
}

function buildProductPayload({
  sellerId,
  brandId,
  profile,
  globalIndex,
  localIndex,
  categoryCache,
  fallbackCategoryId,
}: BuildContext): Record<string, unknown> {
  const seriesIndex = localIndex % profile.series.length;
  const generation = Math.floor(localIndex / profile.series.length);
  const series = profile.series[seriesIndex];
  const color = profile.colors[(globalIndex + localIndex) % profile.colors.length];
  const storage = profile.storageOptions[(globalIndex + localIndex) % profile.storageOptions.length];
  const display = profile.displaySizes[localIndex % profile.displaySizes.length];
  const chipset = profile.chipsets[(globalIndex + localIndex) % profile.chipsets.length];

  const modelVariant = generation > 0 ? `${series} Gen ${generation + 1}` : series;
  const modelName =
    profile.brand === "Apple" ? modelVariant : `${profile.brand} ${modelVariant}`;
  const slugBase = `${modelName} ${storage}GB ${color}`;
  const slug = slugify(`${slugBase} ${globalIndex + 1}`);

  const categoryId = resolveCategoryId(
    profile,
    series,
    modelVariant,
    categoryCache,
    fallbackCategoryId
  );

  const price = Math.round(
    profile.basePrice +
    generation * profile.priceStep +
    seriesIndex * Math.round(profile.priceStep / 2) +
    Math.random() * profile.priceVariance
  );
  const compareAtPrice = price + Math.round(120 + Math.random() * 160);
  const stock = profile.baseStock + ((localIndex + globalIndex) * 3) % 64;

  const images = [
    `https://cdn.example.com/${profile.slugSegment}/${slug}.jpg`,
    `https://cdn.example.com/${profile.slugSegment}/${slug}-alt.jpg`,
  ];

  const description = `${modelName} delivers flagship experiences with a ${display}-inch ${profile.displayTechnology} display, ${chipset} platform, and ${storage}GB of storage in a ${color.toLowerCase()} finish.`;
  const feature = [
    `• ${display}-inch ${profile.displayTechnology} display`,
    `• ${chipset} 5G processor`,
    `• ${storage}GB storage with high-speed flash`,
    `• ${profile.os}`,
    `• ${profile.charging}`,
  ].join("\n");

  const attributes: Record<string, string> = {
    Brand: profile.brand,
    Series: series,
    Model: modelVariant,
    Storage: `${storage}GB`,
    Color: color,
    Display: `${display}\"`,
    Chipset: chipset,
    OS: profile.os,
  };

  const seoTitle = `${modelName} ${storage}GB ${color} | ${profile.brand} ${profile.productType}`;
  const seoDescription = `${modelName} pairs ${profile.displayTechnology} visuals with ${chipset} performance and ${storage}GB storage for discerning users.`;

  const priceFloor = Math.max(price - 40, Math.round(price * 0.88));
  const storageLabel = `${storage}GB`;
  const variantSkuBase = `${profile.slugSegment}-${modelVariant}-${storageLabel}-${color}-${globalIndex + 1}`;
  const variantSku = variantSkuBase
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 64);

  const variants = [
    {
      sku: variantSku,
      price,
      stock,
      inventory: {
        onHand: stock,
        reserved: 0,
        safetyStock: 0,
      },
      attributes: {
        Color: color,
        Storage: storageLabel,
      },
      images,
      isActive: true,
    },
  ];

  return {
    productId: generateProductId(profile.brand, globalIndex),
    name: modelName,
    slug,
    description,
    feature,
    price,
    compareAtPrice,
    currency: "USD",
    stock,
    category: categoryId,
    brand: brandId,
    seller: sellerId,
    status: "Published",
    tag: [
      "phone",
      profile.brand.toLowerCase(),
      profile.slugSegment,
      `${storage}gb`,
      modelVariant.replace(/\s+/g, "-").toLowerCase(),
    ],
    images,
    primaryImageIndex: 0,
    ratingAvg: Math.round((Math.random() * 1.8 + 3.2) * 10) / 10,
    ratingCount: 50 + Math.floor(Math.random() * 250),
    salesCount: 100 + Math.floor(Math.random() * 4000),
    isTrending: profile.brand === "Apple" || profile.brand === "Samsung",
    dimensions: {
      length: Number((16 + Math.random()).toFixed(1)),
      width: Number((7.5 + Math.random() * 0.6).toFixed(1)),
      height: Number((0.75 + Math.random() * 0.2).toFixed(2)),
    },
    weight: Number((185 + Math.random() * 35).toFixed(0)),
    variants,
    attributes,
    seo: {
      title: seoTitle,
      description: seoDescription,
      keywords: [
        profile.brand,
        modelVariant,
        `${profile.brand} smartphone`,
        chipset,
        `${storage}GB phone`,
      ],
    },
    isAdult: false,
    isHazardous: false,
    productType: profile.productType,
    actualPrice: price,
    dealerPrice: Math.round(price * 0.84),
    dedupeKey: `${sellerId.toHexString()}:${slug}`,
    isDeleted: false,
    priceMin: priceFloor,
    priceMax: compareAtPrice,
    cost: Math.round(price * 0.78),
  };
}

type AllocationRuntime = BrandAllocation & { brandId: mongoose.Types.ObjectId };

function buildAllProducts(
  sellerId: mongoose.Types.ObjectId,
  allocations: AllocationRuntime[],
  categoryCache: CategoryCache,
  fallbackCategoryId: string
): Record<string, unknown>[] {
  const products: Record<string, unknown>[] = [];
  let globalIndex = 0;

  for (const allocation of allocations) {
    for (let localIndex = 0; localIndex < allocation.quantity; localIndex += 1) {
      products.push(
        buildProductPayload({
          sellerId,
          profile: allocation.profile,
          brandId: allocation.brandId,
          globalIndex,
          localIndex,
          categoryCache,
          fallbackCategoryId,
        })
      );
      globalIndex += 1;
    }
  }

  return products;
}

async function prepareCategoryCache(
  profiles: BrandProfile[],
  fallbackCategory: CategoryDescriptor
): Promise<CategoryCache> {
  const descriptors = new Map<string, CategoryDescriptor>();
  descriptors.set(fallbackCategory.id, fallbackCategory);

  for (const profile of profiles) {
    if (profile.defaultCategory) {
      descriptors.set(profile.defaultCategory.id, profile.defaultCategory);
    }
    if (profile.categoryRules) {
      for (const rule of profile.categoryRules) {
        descriptors.set(rule.category.id, rule.category);
      }
    }
  }

  const cache: CategoryCache = new Map();
  for (const descriptor of descriptors.values()) {
    const category = await ensureCategory(descriptor.id, descriptor.name);
    cache.set(descriptor.id, category._id as mongoose.Types.ObjectId);
  }

  return cache;
}

async function prepareAllocations(): Promise<AllocationRuntime[]> {
  const allocations: AllocationRuntime[] = [];

  for (const allocation of BRAND_ALLOCATIONS) {
    const brand = await ensureBrand(allocation.profile.brandRecordName, allocation.profile.brandSlug);
    allocations.push({
      ...allocation,
      brandId: brand._id as mongoose.Types.ObjectId,
    });
  }

  return allocations;
}

async function run() {
  const options = buildOptions();
  const mongoUri = process.env.MONGO_URI;
  if (!mongoUri) throw new Error("MONGO_URI environment variable is required");

  console.log(`Connecting to MongoDB...`);
  await mongoose.connect(mongoUri);
  console.log(`Connected. Preparing seed data...`);

  const seller = await User.findById(options.sellerId).select("_id");
  if (!seller) {
    throw new Error(
      `Seller with id ${options.sellerId} was not found. Please create it before seeding.`
    );
  }
  const sellerId = seller._id as mongoose.Types.ObjectId;
  const fallbackCategory: CategoryDescriptor = {
    id: options.categoryId,
    name: options.categoryName,
  };
  const categoryCache = await prepareCategoryCache(
    BRAND_ALLOCATIONS.map((allocation) => allocation.profile),
    fallbackCategory
  );
  const allocations = await prepareAllocations();

  const products = buildAllProducts(sellerId, allocations, categoryCache, fallbackCategory.id);

  const total = products.length;
  console.log("Prepared product distribution:");
  for (const allocation of BRAND_ALLOCATIONS) {
    console.log(`- ${allocation.profile.brand}: ${allocation.quantity}`);
  }
  console.log(`Total products: ${total}`);

  if (options.dryRun) {
    console.log(`Dry run enabled. Generated ${products.length} product payloads.`);
    console.log(products[0]);
    await mongoose.disconnect();
    return;
  }

  const inserted = await Product.insertMany(products, { ordered: false });

  console.log(`Inserted ${inserted.length} products.`);

  await mongoose.disconnect();
  console.log("MongoDB connection closed.");
}

run().catch(async (err) => {
  console.error("Seed script failed:", err);
  try {
    await mongoose.disconnect();
  } catch (disconnectErr) {
    console.error("Failed to disconnect cleanly:", disconnectErr);
  }
  process.exit(1);
});
