import "dotenv/config";
import mongoose from "mongoose";
import Product from "../models/Product";
import Category from "../models/Category";
import Brand from "../models/Brand";
import User from "../models/User";

type PhoneBrand = {
  name: string;
  slug: string;
  models: string[];
  colors: string[];
  basePrice: number;
};

const PHONE_BRANDS: PhoneBrand[] = [
  {
    name: "Apple",
    slug: "apple",
    models: ["iPhone 15", "iPhone 15 Plus", "iPhone 15 Pro", "iPhone 15 Pro Max", "iPhone SE"],
    colors: ["Black", "White", "Blue", "Natural Titanium", "Pink"],
    basePrice: 799,
  },
  {
    name: "Samsung",
    slug: "samsung",
    models: ["Galaxy S24", "Galaxy S24 Plus", "Galaxy S24 Ultra", "Galaxy A55", "Galaxy Z Flip5"],
    colors: ["Phantom Black", "Cream", "Violet", "Graphite", "Ice Blue"],
    basePrice: 699,
  },
  {
    name: "OPPO",
    slug: "oppo",
    models: ["Find X7", "Reno11", "Reno11 Pro", "A79", "F25 Pro"],
    colors: ["Ocean Blue", "Emerald Green", "Sunset Gold", "Space Black", "Silver"],
    basePrice: 349,
  },
  {
    name: "Vivo",
    slug: "vivo",
    models: ["X100", "X100 Pro", "V30", "V30 Pro", "Y36"],
    colors: ["Asteroid Black", "Startrail Blue", "Petals White", "Andes Blue", "Gold"],
    basePrice: 329,
  },
  {
    name: "Xiaomi",
    slug: "xiaomi",
    models: ["Xiaomi 14", "Xiaomi 14 Ultra", "Redmi Note 13", "Redmi K70", "Poco F6"],
    colors: ["Black", "White", "Green", "Orange", "Silver"],
    basePrice: 299,
  },
  {
    name: "OnePlus",
    slug: "oneplus",
    models: ["OnePlus 12", "OnePlus 12R", "OnePlus Open", "Nord 3", "Nord CE 4"],
    colors: ["Silky Black", "Emerald Green", "Glacier Silver", "Iron Gray", "Marble"],
    basePrice: 449,
  },
  {
    name: "Google",
    slug: "google",
    models: ["Pixel 8", "Pixel 8 Pro", "Pixel 8a", "Pixel Fold", "Pixel 7a"],
    colors: ["Obsidian", "Porcelain", "Hazel", "Bay", "Aloe"],
    basePrice: 499,
  },
  {
    name: "Motorola",
    slug: "motorola",
    models: ["Razr 40", "Razr 40 Ultra", "Edge 40", "Edge 40 Pro", "Moto G Power 5G"],
    colors: ["Magenta", "Satin Blue", "Eclipse Black", "Nebula Green", "Lunar Blue"],
    basePrice: 279,
  },
  {
    name: "Sony",
    slug: "sony",
    models: ["Xperia 1 V", "Xperia 5 V", "Xperia 10 V", "Xperia Pro-I", "Xperia 1 IV"],
    colors: ["Black", "Khaki Green", "Silver", "Burgundy", "Slate"],
    basePrice: 699,
  },
  {
    name: "ASUS ROG",
    slug: "asus-rog",
    models: ["ROG Phone 7", "ROG Phone 7 Ultimate", "ROG Phone 8", "ROG Phone 8 Pro", "Zenfone 10"],
    colors: ["Phantom Black", "Storm White", "Rebel Grey", "Blue", "Red"],
    basePrice: 799,
  },
];

const STORAGE_OPTIONS = [128, 256, 512, 1024];
const RAM_OPTIONS = [6, 8, 12, 16];
const DISPLAY_OPTIONS = [6.1, 6.4, 6.7, 6.8];
const CHIPSETS = [
  "Snapdragon 8 Gen 3",
  "Snapdragon 8 Gen 2",
  "Apple A17 Pro",
  "MediaTek Dimensity 9300",
  "Google Tensor G3",
];

function slugify(value: string) {
  return value
    .toLowerCase()
    .trim()
    .replace(/['"]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function pick<T>(items: T[], index: number) {
  return items[index % items.length];
}

async function getSellerId() {
  if (process.env.SEED_SELLER_ID && mongoose.isValidObjectId(process.env.SEED_SELLER_ID)) {
    const seller = await User.findById(process.env.SEED_SELLER_ID).select("_id");
    if (seller) return seller._id;
  }

  const seller = await User.findOne({ status: "ACTIVE" }).select("_id");
  if (!seller) {
    throw new Error("No active seller found. Create one user first or set SEED_SELLER_ID in .env");
  }

  return seller._id;
}

async function ensurePhoneCategory() {
  const existing = await Category.findOne({
    $or: [{ categoryId: "phones" }, { categoryName: "Smartphones" }],
  }).select("_id");

  if (existing) return existing._id;

  const category = await Category.create({
    categoryId: "phones",
    categoryName: "Smartphones",
    description: "Phone products generated by seed script",
  });

  return category._id;
}

async function ensureBrand(brand: PhoneBrand) {
  const existing = await Brand.findOne({
    $or: [{ slug: brand.slug }, { name: brand.name }],
  }).select("_id");

  if (existing) return existing._id;

  const created = await Brand.create({
    name: brand.name,
    slug: brand.slug,
    isActive: true,
  });

  return created._id;
}

function buildPhoneProduct(params: {
  brand: PhoneBrand;
  brandId: mongoose.Types.ObjectId;
  categoryId: mongoose.Types.ObjectId;
  sellerId: mongoose.Types.ObjectId;
  brandIndex: number;
  localIndex: number;
  globalIndex: number;
  runId: string;
}) {
  const { brand, brandId, categoryId, sellerId, brandIndex, localIndex, globalIndex, runId } = params;

  const model = pick(brand.models, localIndex);
  const color = pick(brand.colors, globalIndex + brandIndex);
  const storage = pick(STORAGE_OPTIONS, localIndex + brandIndex);
  const ram = pick(RAM_OPTIONS, globalIndex);
  const display = pick(DISPLAY_OPTIONS, globalIndex + localIndex);
  const chipset = pick(CHIPSETS, globalIndex + brandIndex);

  const price = brand.basePrice + localIndex * 18 + brandIndex * 9 + storage / 8;
  const roundedPrice = Math.round(price);
  const compareAtPrice = roundedPrice + 80 + ((globalIndex * 7) % 90);
  const stock = 15 + ((globalIndex * 3) % 85);

  const name = `${brand.name} ${model} ${storage}GB ${color}`;
  const slug = slugify(`${name}-${runId}-${globalIndex + 1}`);
  const sku = slug.toUpperCase().replace(/[^A-Z0-9]+/g, "-").slice(0, 64);

  const images = [
    `https://cdn.example.com/phones/${slug}.jpg`,
    `https://cdn.example.com/phones/${slug}-back.jpg`,
  ];

  return {
    productId: `PHN-${runId.toUpperCase()}-${String(globalIndex + 1).padStart(3, "0")}`,
    name,
    slug,
    description: `${name} with ${ram}GB RAM, ${storage}GB storage, ${display}-inch display, and ${chipset} chipset.`,
    feature: [
      `${display}-inch AMOLED display`,
      `${chipset} processor`,
      `${ram}GB RAM and ${storage}GB storage`,
      "5G network support",
      "Fast charging with long battery life",
    ].join("\n"),
    brand: brandId,
    category: categoryId,
    seller: sellerId,
    price: roundedPrice,
    compareAtPrice,
    currency: "USD",
    stock,
    status: "Published",
    tag: ["phone", "smartphone", brand.slug, `${storage}gb`, color.toLowerCase().replace(/\s+/g, "-")],
    images,
    primaryImageIndex: 0,
    ratingAvg: Number((3.8 + ((globalIndex % 12) / 10)).toFixed(1)),
    ratingCount: 25 + globalIndex * 2,
    ratingSum: 0,
    salesCount: 50 + globalIndex * 11,
    isTrending: globalIndex % 5 === 0,
    dimensions: {
      length: 16,
      width: 7.6,
      height: 0.8,
    },
    weight: 180 + (globalIndex % 45),
    variants: [
      {
        sku,
        price: roundedPrice,
        stock,
        inventory: {
          onHand: stock,
          reserved: 0,
          safetyStock: 2,
        },
        attributes: {
          Color: color,
          Storage: `${storage}GB`,
          RAM: `${ram}GB`,
        },
        images,
        isActive: true,
      },
    ],
    attributes: {
      Brand: brand.name,
      Model: model,
      Color: color,
      Storage: `${storage}GB`,
      RAM: `${ram}GB`,
      Display: `${display} inch`,
      Chipset: chipset,
      Network: "5G",
    },
    seo: {
      title: `${name} | Smartphone`,
      description: `${name} available with ${ram}GB RAM, ${storage}GB storage, 5G, and fast charging.`,
      keywords: [brand.name, model, "phone", "smartphone", "5G"],
    },
    isAdult: false,
    isHazardous: false,
    productType: "Phone",
    actualPrice: roundedPrice,
    dealerPrice: Math.round(roundedPrice * 0.85),
    dedupeKey: `${sellerId.toString()}:${slug}`,
    isDeleted: false,
  };
}

async function run() {
  const mongoUri = process.env.MONGO_URI;
  if (!mongoUri) throw new Error("MONGO_URI is required in .env");

  await mongoose.connect(mongoUri);
  console.log("Connected to MongoDB");

  const sellerId = await getSellerId();
  const categoryId = await ensurePhoneCategory();
  const runId = Date.now().toString(36);

  const products: Record<string, unknown>[] = [];

  for (let brandIndex = 0; brandIndex < PHONE_BRANDS.length; brandIndex += 1) {
    const brand = PHONE_BRANDS[brandIndex];
    const brandId = await ensureBrand(brand);

    for (let localIndex = 0; localIndex < 20; localIndex += 1) {
      products.push(
        buildPhoneProduct({
          brand,
          brandId: brandId as mongoose.Types.ObjectId,
          categoryId: categoryId as mongoose.Types.ObjectId,
          sellerId: sellerId as mongoose.Types.ObjectId,
          brandIndex,
          localIndex,
          globalIndex: products.length,
          runId,
        })
      );
    }
  }

  console.log(`Prepared ${products.length} phone products`);

  if (process.env.SEED_DRY_RUN === "true") {
    console.log("Dry run enabled. First product example:");
    console.log(JSON.stringify(products[0], null, 2));
    await mongoose.disconnect();
    return;
  }

  const inserted = await Product.insertMany(products, { ordered: false });
  console.log(`Inserted ${inserted.length} phone products successfully`);

  await mongoose.disconnect();
  console.log("MongoDB connection closed");
}

run().catch(async (error) => {
  console.error("Failed to seed 200 phone products:", error);
  await mongoose.disconnect().catch(() => undefined);
  process.exit(1);
});
